[build-tf]
build_commands = [
  [
    "rm", "-rf",  "~/.tdd-providers"
  ],
  [
    "mkdir", "-p", "~/.tdd-providers/registry.terraform.io/Proxmox-Cloud/pxc/$VERSION/linux_$ARCH/"
  ],
  [
    "go", "build", "-ldflags=-X main.version=$VERSION", "-o", "~/.tdd-providers/registry.terraform.io/Proxmox-Cloud/pxc/$VERSION/linux_$ARCH/terraform-provider-pxc_v$VERSION"
  ]
]


[local]
dyn_version_py_path = "src/pve_cloud_rpc/_version.py"
dep_build_keys = [
  "version.py-pve-cloud"
]

[redis]
version_key = "version.tf-prov-proxmox-cloud"
